### PR TITLE
Custom variables refactor

### PR DESCRIPTION
**Pull request by sogehige**
###### FEATURES & DESCRIPTION
- [X] Custom variables registry to set variables
- [x] New variable types: eval, number, text, options 
- [x] Update widget to watch variables from registry
- [x] Update `$!_#` and `$_`# message filters
- [x] Add readonly toggle for change through chat

###### Note
No migration for custom variables

###### ISSUES TO FIX
- [x] If variables are added in registry, widget should not need refresh
- [x] If variable is deleted in registry, watch variable should be removed
- [x] Add sender variable for eval if used in keyword or custom command, otherwise null
- [x] `Not Available` additional info should not be shown when there is at least one item (like readonly)
- [x] Add sender and param to eval
- [x] Add delete of variables from watchlist

###### CHECKLIST
- [x] Added tests _if applicable_
- [x] Add test for read only variables
- [x] Translations added
- [x] Commits Squashed
- [x] Test Passing

### CODE REVIEW

**Comment by sogehelper** [comment]
Can you pls add new filter, what will just output variable value, without opportunity to change in chat?
i mean if mods will try to change it, they will can't (owner same)
Just simple output of value.

**Comment by sogehige** [comment]
@sogehelper I can add readonly toggle for variable for chat updates

**Comment by sogehelper** [comment]
Ok, it's enought, i think..
But better have filter.

**Comment by sogehige** [comment]
There cannot be filter for everything

**Pull request merged**
