### PR TITLE
feat(events): do not fire join/part event if user ignored

### PR DESCRIPTION
**Pull request by Banonevar**
###### CHECKLIST

- [ ] tests are changed or added
- [ ] documentation is changed or added
- [ ] locales are changed or added
- [ ] db relationship (tools/database) are changed or added
- [ ] commit message follows [commit guidelines](https://github.com/sogehige/sogeBot/blob/master/CONTRIBUTING.md#commit-guidelines)

### CODE REVIEW

**Comment by sogehige** [comment]
This is already done at

https://github.com/sogehige/sogeBot/blob/master/src/bot/api.js#L355

and 

https://github.com/sogehige/sogeBot/blob/master/src/bot/api.js#L363

**Comment by Banonevar** [comment]
No, it's not working. Thats why i created this PR, because i have much annoyed join/part events

**Comment by sogehige** [comment]
Then it should be fixed on right place :)

Dne po 10. 6. 2019 17:22 uživatel Banonevar <notifications@github.com>
napsal:

**Comment by Banonevar** [comment]
Well, you can decline mine PR, but this is working for me.

**Comment by sogehige** [comment]
Yes , it's working but it doesn't fix broken code just adding another check
elsewhere

Dne po 10. 6. 2019 17:56 uživatel Banonevar <notifications@github.com>
napsal:

**Comment by Banonevar** [comment]
I have no idea where is bug.

**Pull request closed without merging**
