### PR TITLE
fix: add run-node package, requried for pre-commit hook

### PR DESCRIPTION
**Pull request by Banonevar**
This package is missed in package.json, so if you haven't this package, you cannot commit.

###### CHECKLIST

- [ ] tests are changed or added
- [ ] documentation is changed or added
- [ ] locales are changed or added
- [ ] db relationship (tools/database) are changed or added
- [ ] commit message follows [commit guidelines](https://github.com/sogehige/sogeBot/blob/master/CONTRIBUTING.md#commit-guidelines)

### CODE REVIEW

**Comment by sogehige** [comment]
Interesting, what it is for?

**Comment by Banonevar** [comment]
For running 
```
"husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
"lint-staged": {
    "*.ts": [
      "eslint --fix",
      "git add"
    ],
    "*.json": [
      "jsonlint",
      "git add"
    ]
  },
```
lint-staged from code above.

I found an issue about that https://github.com/typicode/husky/issues/683, seems like it related to linux-only machines.

After installing `run-node` it's gone, so it's temporary workaround.

**Comment by sogehige** [comment]
Still not sure what issue was. I am using lint-staged without issues on Windows and Unix.

**Comment by Banonevar** [comment]
Hm, just reinstalled node_modules and also cannot reproduce now.

Well, i'm closing this PR, maybe it was one-time-bug of mine env.

**Pull request closed without merging**
