### PR TITLE
fix(locales): set correct translation for reset

### PR DESCRIPTION
**Pull request by tarumes**
###### CHECKLIST

- [ ] tests are changed or added
- [ ] documentation is changed or added
- [ ] locales are changed or added
- [ ] db relationship (tools/database) are changed or added
- [ ] commit message follows [commit guidelines](https://github.com/sogehige/sogeBot/blob/master/CONTRIBUTING.md#commit-guidelines)

### CODE REVIEW

**Comment by Banonevar** [comment]
PR name not followed https://github.com/sogehige/sogeBot/blob/master/CONTRIBUTING.md#commit-guidelines

**Comment by Banonevar** [comment]
i think it must be something like `fix(locales): wrong language for reset button`

**Comment by gOOvER** [comment]
Translations should be handled in a separate Place. I try to translate it to german, but IT's a mess. aber second Commit change the files:/

**Comment by Banonevar** [comment]
> Translations should be handled in a separate Place. I try to translate it to german, but IT's a mess. every second Commit change the lang files:/

Doubled 👍

**Pull request merged**
