### PR TITLE
feat(spotify): write current song to txt file

### PR DESCRIPTION
**Pull request by acuneen**
###### CHECKLIST

- [ ] tests are changed or added
- [ ] documentation is changed or added
- [ ] locales are changed or added
- [ ] db relationship (tools/database) are changed or added
- [x] commit message follows [commit guidelines](https://github.com/sogehige/sogeBot/blob/master/CONTRIBUTING.md#commit-guidelines)

### CODE REVIEW

**Comment by sogehige** [comment]
Why do you need current song in file?

**Comment by acuneen** [comment]
Having the current song in a text file makes it easier to display it on the stream layout. 
For example the .txt file can be used as an OBS source.

**Comment by sogehige** [comment]
You can already show current songs with text overlay. Also, this is basically function of https://github.com/sogehige/sogeTicker which was deprecated.

**Comment by sogehige** [comment]
Don't get me wrong, I don't feel it is usable because usually you are running bot on server, not your desktop, where txt file is unusable.

**Pull request closed without merging**
