### PR TITLE
[WIP] system/quotes

### PR DESCRIPTION
**Pull request by sogehige**
###### FEATURES & DESCRIPTION
- [x] Adding quotes, id should be simple number
  - `!quote add -quote "<text>"` - default tag is general
  - `!quote add -tag some_tag, tag2 -quote <text>`
  - `$sender, quote <id> '<text>' was added (tags: ...)`
- [x] Update quotes by id
  - `!quote set -tag some_tag -id <id>`
  - tag and quote parameters are optional
- [x] `!quote delete <id>`
- [x] `!quote list` > link for public quote page
- [x] Enable/Disable system through ui
- [x] Enable/Disable system through chat
  - `!system enable/disable quotes`?
- [x] Changeable commands `!quote`, `!quote add`, etc
- [x] Add tag system for quotes
  - `!quote some_tag` - random quote from tag
  - `!quote id` - direct quote
- [x] Add UI visuals to see if settings got changes -> like save if you don't want to lose your changes

###### ISSUES REFS
#368 

###### CHECKLIST
- [x] Added tests _if applicable_
- [x] Docs Updated _if applicable_
- [x] Translations added
- [x] Commits Squashed

### CODE REVIEW

**Comment by sogehelper** [comment]
Will be good have group of quotes. And filter of this group, what will print random quote, mabye others filter like second quote from group
Example i will have group `dota_phrases` and will add some quotes in this group
i will like use `$quotes_dota_phrases_random` (for example) filter in some command, for print some random quote from this group, rly
Right now i'm using external api for that, but will good if we have this in bot :P

**Comment by sogehige** [comment]
Would be enough to have tags for quotes?

I mean, currently its `!quote 1` -> print quote 1
with tags you will be able to do `!quote some_tag` - random quote from tag
`

**Comment by sogehelper** [comment]
But i want print quote in command text
like i will have some command with another text + quote
example:
quotes in dota_phrases group: Divine, Crusader
command: !test
response: your rank from dota 2 is: (randomquote)
__
Chat:
user: !test
bot: your rank from dota 2 is: Divine
___
I know i can do via EVAL but it's simple example of using, i need it for others point 🍡

**Comment by sogehige** [comment]
I don't think I ever see quotes used like that, this is more for custom variables, although I am ok with tag use

**Comment by sogehelper** [comment]
Eval not user friendly how not know javascript

**Comment by sogehige** [comment]
Thats why we should share snippets and help others do that.

**Pull request merged**
